% CLEAN_INTERPRETER
% Stage 2: Target Detection, Coherent Successive Target Cancellation (CLEAN),
% Physical Axis Calibration, and High-Resolution Visualization.
%
% Reference:
%   Martin Braun, "OFDM Radar Algorithms in Mobile Communication Networks", KIT, 2014, Sec. 3.3.7.
%
% Input:
%   radar_data.mat - Generated by receiver_pipeline.m

fprintf(">> Running CLEAN Target Interpreter...\n");

%% 1. Load Radar Periodogram Data
if ~isfile('radar_data.mat')
    error("radar_data.mat not found. Please run receiver_pipeline.m first!");
end
load('radar_data.mat');

%% 2. Iterative Coherent Target Cancellation (CLEAN Algorithm)
num_targets = 2; % Number of moving targets to detect and cancel
fprintf("  Executing CLEAN algorithm for %d targets...\n", num_targets);

[CPer_clean, targets_found] = run_coherent_clean(CPer_base, W_2D_unshifted, N_per, M_per, Nfft, n_symbols, num_targets);

%% 3. Power Scaling and Decibel Conversion
Per_dB_base  = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_base).^2  + 1e-9);
Per_dB_clean = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_clean).^2 + 1e-9);

%% 4. Calibrated Physical Axes
[axis_range, axis_velocity] = calculate_physical_axes(fs, fc, Nfft, Ncp, N_per, M_per, c);

% Print detected target physical coordinates
fprintf("  Detected Targets (Physical Coordinates):\n");
for i = 1 : size(targets_found, 1)
    r_m = axis_range(targets_found(i, 1));
    v_ms = axis_velocity(targets_found(i, 2));
    fprintf("    Target %d: Range = %.2f m, Velocity = %+.2f m/s\n", i, r_m, v_ms);
end

%% 5. Visualization (Before vs After CLEAN)
if exist('ENABLE_VISUALIZATIONS', 'var') && ENABLE_VISUALIZATIONS
    if exist('WIFI_STANDARD', 'var')
        fig_title = sprintf('Wi-Fi Radar - Target Detection & CLEAN Cancellation (%s)', WIFI_STANDARD);
    else
        fig_title = 'Wi-Fi Radar - Target Detection & CLEAN Cancellation';
    end
    plot_clean_results(Per_dB_base, Per_dB_clean, axis_velocity, axis_range, targets_found, fig_title);
end
