% CLEAN_INTERPRETER
% Stage 2: Target Detection, Coherent Successive Target Cancellation (CLEAN),
% Physical Axis Calibration, and High-Resolution Visualization.
%
% Reference:
%   Martin Braun, "OFDM Radar Algorithms in Mobile Communication Networks", KIT, 2014, Sec. 3.3.7.
%
% Input:
%   radar_data.mat - Generated by receiver_pipeline.m

fprintf(">> Running CLEAN Target Interpreter...\n");

%% 1. Load Radar Periodogram Data
if ~isfile('radar_data.mat')
    error("radar_data.mat not found. Please run receiver_pipeline.m first!");
end
load('radar_data.mat');

%% 2. Iterative Coherent Target Cancellation (CLEAN Algorithm)
CPer_clean = CPer_base;
num_targets = 2; % Number of moving targets to detect and cancel
targets_found = [];

fprintf("  Executing CLEAN algorithm for %d targets...\n", num_targets);

for i = 1 : num_targets
    % Find maximum amplitude in current residual periodogram
    [~, idx] = max(abs(CPer_clean(:)));
    [r_idx, d_idx] = ind2sub([N_per, M_per], idx);
    targets_found = [targets_found; r_idx, d_idx];
    
    complex_val = CPer_clean(r_idx, d_idx);
    
    % Reconstruct target point spread function in frequency/time domain
    P = zeros(N_per, M_per);
    P(r_idx, d_idx) = 1;
    H_full = fft(ifft(ifftshift(P, 2), M_per, 2), N_per, 1);
    
    % Apply 2D window matching the measurement pipeline
    H_crop_win = H_full(1:Nfft, 1:n_symbols) .* W_2D_unshifted;
    
    % Periodogram of the reconstructed single target
    CPer_target = fftshift(fft(ifft(H_crop_win, N_per, 1), M_per, 2), 2);
    CPer_target_norm = CPer_target / CPer_target(r_idx, d_idx);
    
    % Coherent subtraction of target and its sidelobes
    CPer_clean = CPer_clean - complex_val * CPer_target_norm;
    
    fprintf("    Target %d localized at Range bin %d, Doppler bin %d (Amp: %.2f dB)\n", ...
        i, r_idx, d_idx, 20*log10(abs(complex_val)));
end

%% 3. Power Scaling and Decibel Conversion
Per_dB_base  = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_base).^2  + 1e-9);
Per_dB_clean = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_clean).^2 + 1e-9);

%% 4. Calibrated Physical Axes
% Range Axis [m]
delta_r = c / (2 * fs);
max_range = delta_r * Nfft;
axis_range = linspace(0, max_range, N_per);

% Velocity / Doppler Axis [m/s]
T_sym_total = (Nfft + Ncp) / fs;
v_unamb = c / (2 * fc * T_sym_total);
axis_velocity = linspace(-v_unamb/2, v_unamb/2, M_per);

% Print detected target physical coordinates
fprintf("  Detected Targets (Physical Coordinates):\n");
for i = 1 : size(targets_found, 1)
    r_m = axis_range(targets_found(i, 1));
    v_ms = axis_velocity(targets_found(i, 2));
    fprintf("    Target %d: Range = %.2f m, Velocity = %+.2f m/s\n", i, r_m, v_ms);
end

%% 5. Visualization (Before vs After CLEAN)
fig = figure('Name', 'Wi-Fi Radar - Target Detection & CLEAN Cancellation', ...
             'Color', 'white', 'Position', [100, 100, 1200, 520]);

c_lims = [max(Per_dB_base(:)) - 60, max(Per_dB_base(:))];

% Subplot 1: Original Range-Doppler Map
subplot(1, 2, 1);
imagesc(axis_velocity, axis_range, Per_dB_base);
axis xy; colormap('jet');
title('1. Original Range-Doppler Map (Before CLEAN)');
xlabel('Velocity [m/s]'); ylabel('Range [m]');
ylim([0 150]); xlim([-60 60]); clim(c_lims);
hold on;
plot(axis_velocity(targets_found(:, 2)), axis_range(targets_found(:, 1)), ...
     'kx', 'MarkerSize', 12, 'LineWidth', 2.2);
legend('Localized Targets', 'Location', 'northeast');
grid on;

% Subplot 2: Cleaned Residual Map
subplot(1, 2, 2);
imagesc(axis_velocity, axis_range, Per_dB_clean);
axis xy; colormap('jet');
title('2. Residual Background (After Coherent CLEAN)');
xlabel('Velocity [m/s]'); ylabel('Range [m]');
ylim([0 150]); xlim([-60 60]); clim(c_lims);
cbar = colorbar; cbar.Label.String = 'Power [dB]';
grid on;

%% 6. Save Figure to results/figures/
[current_dir, ~, ~] = fileparts(mfilename('fullpath'));
fig_dir = fullfile(current_dir, '..', 'results', 'figures');
if ~exist(fig_dir, 'dir')
    mkdir(fig_dir);
end
fig_file = fullfile(fig_dir, 'range_doppler_clean_results.png');
saveas(fig, fig_file);
fprintf("  Result plot saved to: %s\n", fig_file);
