function targets_found = step4_interpreter(radar_data, fs, fc, c, WIFI_STANDARD, ENABLE_VISUALIZATIONS)
% CLEAN_INTERPRETER
% Stage 2: Target Detection, Coherent Successive Target Cancellation (CLEAN),
% Physical Axis Calibration, and High-Resolution Visualization.
%
% Inputs:
%   radar_data    - Struct generated by receiver_pipeline
%   fs            - Sampling frequency
%   fc            - Carrier frequency
%   c             - Speed of light
%   WIFI_STANDARD - Standard string
%   ENABLE_VISUALIZATIONS - boolean

    fprintf(">> Running CLEAN Target Interpreter...\n");

    %% 1. Unpack Radar Data
    CPer_base = radar_data.CPer_base;
    W_2D_unshifted = radar_data.W_2D_unshifted;
    N_per = radar_data.N_per;
    M_per = radar_data.M_per;
    Nfft = radar_data.Nfft;
    n_symbols = radar_data.n_symbols;
    Ncp = radar_data.Ncp;

    %% 2. Iterative Coherent Target Cancellation (CLEAN Algorithm)
    num_targets = 2; % Number of moving targets to detect and cancel
    fprintf("  Executing CLEAN algorithm for %d targets...\n", num_targets);

    [CPer_clean, targets_found] = run_coherent_clean(CPer_base, W_2D_unshifted, N_per, M_per, Nfft, n_symbols, num_targets);

    %% 3. Power Scaling and Decibel Conversion
    Per_dB_base  = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_base).^2  + 1e-9);
    Per_dB_clean = 10*log10((1 / (Nfft * n_symbols)) * abs(CPer_clean).^2 + 1e-9);

    %% 4. Calibrated Physical Axes
    [axis_range, axis_velocity] = calculate_physical_axes(fs, fc, Nfft, Ncp, N_per, M_per, c);

    % Print detected target physical coordinates
    fprintf("  Detected Targets (Physical Coordinates):\n");
    for i = 1 : size(targets_found, 1)
        r_m = axis_range(targets_found(i, 1));
        v_ms = axis_velocity(targets_found(i, 2));
        fprintf("    Target %d: Range = %.2f m, Velocity = %+.2f m/s\n", i, r_m, v_ms);
    end

    %% 5. Visualization (Before vs After CLEAN)
    if ENABLE_VISUALIZATIONS
        fig_title = sprintf('Wi-Fi Radar - Target Detection & CLEAN Cancellation (%s)', WIFI_STANDARD);
        clean_results(Per_dB_base, Per_dB_clean, axis_velocity, axis_range, targets_found, fig_title);
    end
end
